create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    essay_id text not null,
    rating smallint not null check (rating between 1 and 5),
    author text not null default 'Anonym',
    message text not null check (char_length(message) between 1 and 2000),
    created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "Feedback darf gelesen werden" on public.feedback;
create policy "Feedback darf gelesen werden"
    on public.feedback for select
    to anon, authenticated
    using (true);

drop policy if exists "Feedback darf erstellt werden" on public.feedback;
create policy "Feedback darf erstellt werden"
    on public.feedback for insert
    to anon, authenticated
    with check (rating between 1 and 5 and char_length(message) between 1 and 2000);
